BookStore/Models/AlertViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreUI.Models
{
    public class AlertViewModel
    {
        public AlertViewModel()
        {

        }
        public AlertViewModel(string message, AlertType type)
        {
            Message = message;
            Type = type;
        }

        public string Message { get; set; }
        public AlertType Type { get; set; }


    }
    public enum AlertType
    {
        Information = 0,
        Warning = 1,
        Error = 2
    }
}

BookStore/Controllers/AlertController.cs
using BookStoreUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreUI.Controllers
{
    public class AlertController : Controller
    {
        // GET: Alert
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Returns Alert Notification Partial View.
        /// </summary>
        /// <returns></returns>
        public ActionResult AlertPV()
        {
            var alert = new AlertViewModel();
            if (TempData["Alert"] != null)
                alert = (AlertViewModel)TempData["Alert"];

            return PartialView("_Alert", alert);
        }
    }
}

BookStore/Controllers/BookController.cs
using BookStore.Application.Common;
using BookStore.Application.Common.Interfaces;
using BookStore.Application.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;

namespace BookStoreUI.Controllers
{
    public class BookController : Controller
    {
        private readonly ICurrentUserService _currentUserService;
        private readonly IBookService _bookService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IImageUpload _imageUpload;
        public BookController(IBookService bookService,
            ICurrentUserService currentUserService,
            IImageUpload imageUpload,
            IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _currentUserService = currentUserService;
            _imageUpload = imageUpload;
            _bookService = bookService;
        }

        // GET: BookController
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Index(int currentPage = 1)
        {

            var allBooks = await _bookService.GetAllBooks(currentPage, 10);

            return View(allBooks);
        }
        [Authorize(Roles = "Administrator")]

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Route("book-details/{id:int:min(1)}", Name = "bookDetailsRoute")]
        public async Task<ViewResult> GetBook(int id)
        {
            var data = await _bookService.GetBookById(id);

            if (TempData["Alert"] != null)
                ViewBag.AlertMessage = TempData["Alert"];


            return View(data);
        }
        [Authorize(Roles = "Administrator")]

        public ActionResult Create(bool isSuccess = false, int bookId = 0)
        {

            var model = new BookCreateViewModel();

            return View(model);
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Create(BookCreateViewModel bookCreateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bookCreateViewModel);
            }

            if (bookCreateViewModel.CoverPhoto != null)
            {

                string folder = "books/cover/";
                string rootPath = _webHostEnvironment.WebRootPath;

                bookCreateViewModel.CoverImageUrl = await _imageUpload.UploadImage(folder, bookCreateViewModel.CoverPhoto, rootPath);
            }

            int id = await _bookService.AddNewBook(bookCreateViewModel);

            return RedirectToAction(nameof(Index), new { isSuccess = true, bookId = id });

        }

        // GET: BookController/Edit/5
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Edit(int id)
        {
            var data = await _bookService.GetBookById(id);

            return View(data);
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Edit(int id, BookEditViewModel bookEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bookEditViewModel);
            }
            if (bookEditViewModel.CoverPhoto != null)
            {

                string folder = "books/cover/";
                string rootPath = _webHostEnvironment.WebRootPath;

                bookEditViewModel.ExistingImageUrl = await _imageUpload.UploadImage(folder, bookEditViewModel.CoverPhoto, rootPath);
            }
            int returnBookId = await _bookService.UpdateBook(id, bookEditViewModel);

            return RedirectToAction(nameof(Index), new { isSuccess = true, bookId = id });

        }



        //POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _bookService.DeleteBook(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        [Authorize(Roles = "Reader")]

        public async Task<ActionResult> BorrowRequest(int bookId)
        {
            try
            {
                if (bookId != 0)
                {
                    //var user = User?.Claims;

                    //return View("Claims", user);

                    var userId = _currentUserService.UserId;
                    if (await _bookService.CheckIfBorrowed(bookId, userId))
                    {
                        TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.DuplicateBookRequest, AlertType.Warning));
                        return RedirectToRoute("bookDetailsRoute", new { id = bookId });
                    }
                    await _bookService.RequestForBorrow(bookId, userId);

                    TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.BookRequestSuccess, AlertType.Information));
                }
            }
            catch (Exception)
            {
                TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.DuplicateBookRequest, AlertType.Error)); ;
            }

            return RedirectToRoute("bookDetailsRoute", new { id = bookId });
        }

        [Route("my-book")]
        [HttpGet]
        public async Task<ActionResult> MyBook()
        {
            return View();
        }

    }
}

BookStore/Controllers/BookRequestController.cs
using BookStore.Application.Common;
using BookStore.Application.Common.Interfaces;
using BookStore.Application.Common.Model;
using BookStore.Application.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreUI.Controllers
{

    public class BookRequestController : Controller
    {
        readonly IEmailService _emailService;
        IIdentityService _identityService;
        private readonly IBookRequestService _bookRequestService;

        public BookRequestController(IBookRequestService bookRequestService,
            IEmailService emailService,
            IIdentityService identityService)
        {
            _emailService = emailService;
            _identityService = identityService;
            _bookRequestService = bookRequestService;
        }
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(int currentpage = 1)
        {

            if (TempData["Alert"] != null)
                ViewBag.AlertMessage = TempData["Alert"];


            int pageSize = 10;
            var result = await _bookRequestService.GetRequestedBookList(currentpage, pageSize);

            return View(result);
        }
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetApproveBook(int currentpage = 1)
        {

            int pageSize = 10;
            var result = await _bookRequestService.GetApprovedBook(currentpage, pageSize);

            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> ApproveBook(BookApproveViewModel model)
        {
            try
            {
                await _bookRequestService.ApproveBook(model);
                TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.ApproveBookRequest, AlertType.Information));
            }
            catch (Exception ex)
            {
                TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.Error, AlertType.Error));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> ReturnBook(BookReturnViewModel model)
        {
            try
            {
                await _bookRequestService.ReturnBook(model);
                TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.ApproveBookRequest, AlertType.Information));
            }
            catch (Exception ex)
            {
                TempData["Alert"] = JsonConvert.SerializeObject(new AlertViewModel(AlertMessage.Error, AlertType.Error));
            }

            return RedirectToAction("Index");
        }

    }
}

BookStore/Views/Shared/_Alert.cshtml
@model BookStoreUI.Models.AlertViewModel
@{
    Layout = null;
    string alertClass = string.Empty;
    string title = string.Empty;
    switch (Model.Type)
    {
        case BookStoreUI.Models.AlertType.Information:
            alertClass = "alert-success";
            title = "Success";
            break;
        case BookStoreUI.Models.AlertType.Error:
            alertClass = "alert-danger";
            title = "Error";
            break;
        case BookStoreUI.Models.AlertType.Warning:
            alertClass = "alert-warning";
            title = "Warning";
            break;
    }

}

<div class="alert @alertClass alert-dismissible" role="alert" style="display:block">
    <strong>@title !! </strong> @Model.Message
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<script>
    $('.close').click(function () {
        $('.alert').hide();
    });
</script>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        /* Stackoverflow preview fix, please ignore */
        .navbar-nav {
            flex-direction: row;
        }

        .nav-link {
            padding-right: .5rem !important;
            padding-left: .5rem !important;
        }

        /* Fixes dropdown menus placed on the right side */
        .ml-auto .dropdown-menu {
            left: auto !important;
            right: 0px;
        }

        .bg-custom-1 {
            background-color: #85144b;
        }

        .bg-custom-2 {
            background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);
        }
        .no-data {
            text-align: center;
        }
    </style>
</head>
<body>
    @{
        BookStoreUI.Models.AlertViewModel alert = null;

        if (ViewBag.AlertMessage != null)
        {
            alert = new BookStoreUI.Models.AlertViewModel();
            alert = Newtonsoft.Json.JsonConvert.DeserializeObject<BookStoreUI.Models.AlertViewModel>(ViewBag.AlertMessage.ToString());

        }
    }


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Manage Books</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="BookRequest" asp-action="Index">Borrow Request</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="ListAllUser" asp-controller="Manage">User</a>
                        </li>
                    }

                </ul>
                <ul class="navbar-nav ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="~/images/profile.png" width="60" height="60" class="rounded-circle">
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">@User.Identity.Name</a>
                                <hr />
                                @if (User.IsInRole("Reader"))
                                {
                                    <a asp-controller="MyBook" asp-action="Index"a class="p-3 dropdown-item">My Book</a>

                                }

                                <a asp-controller="Account" asp-action="Profile" class="p-3 dropdown-item">Profile</a>
                                <a asp-controller="Account" asp-action="Logout" class="p-3 dropdown-item">Logout</a>

                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">Login</a>
                        </li>
                    }

                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Reader"))
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login">My Book</a>
                            </li>
                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">Login</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Profile" class="btn btn-outline-primary">Hello! @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }*@


                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (alert != null)
            {
                await Html.RenderPartialAsync("_Alert", alert);
            }



            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BookStore/Views/Shared/_bookThumbnail.cshtml
@model BookListViewModel

<div class="card mb-4 shadow-sm">
    <img src="@(string.IsNullOrEmpty(Model.CoverImageUrl) ? "/images/noimage.png" : Model.CoverImageUrl)" class="img-thumbnail" />
    <div class="card-body">
        <h3 class="card-title">@(string.IsNullOrEmpty(Model.Title) ? "Name is not available" : Model.Title)</h3>
        <p class="card-text">@(string.IsNullOrEmpty(Model.Description) ? "Description is not availabe": Model.Description)</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a asp-route="bookDetailsRoute" asp-route-id="@Model.Id"
                   class="btn btn-sm btn-outline-secondary">View details</a>
            </div>
            <small class="text-muted">@(string.IsNullOrEmpty(Model.Author) ? "NA" : Model.Author)</small>
        </div>
    </div>
</div>